[package]
name = "hijiki"
version = "0.1.0"
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
wgpu = "*"
shaderc = "*"
openexr = "*"
rand = "*"
winit = "*"
tobj = "*"
strum = "*"
strum_macros = "*"
structopt = "*"
bvh = "*"
